import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, BookOpen, Clock, TrendingUp, Users } from "lucide-react";
import type { Course, Student, StudyMaterial, Teacher } from "@/types/domain";
import { toast } from "sonner";
import { apiAuthRequest } from "@/lib/api";
import { deleteFileFromCloudinary } from "@/lib/cloudinary-upload";
import { loadAuthSession } from "@/lib/auth";
import { useQueryClient, useMutation } from "@tanstack/react-query";
import { useTeacherData, type BackendCourse, type BackendClass, type BackendStudent, type BackendAssignment, type BackendQuiz, type AssignmentSubmission, type QuizSubmission, type BackendTimetableSlot, type BackendGradebookEntry } from "@/hooks/use-teacher-data";
import ChaptersTab from "./chapters/ChaptersTab";
import MaterialsTab from "./materials/MaterialsTab";
import OverviewTab from "./overview/OverviewTab";
import PreviewTab from "./preview/PreviewTab";
import StudentsSection from "./students/StudentsSection";

interface Props {
  teacher: Teacher;
  selectedClass: Course | null;
  onSelectClass: (course: Course | null) => void;
  onNavigate: (nav: string, options?: { assignmentId?: number; testId?: number }) => void;
  allClasses?: BackendClass[];
}

type ActiveTab =
  | "overview"
  | "chapters"
  | "materials"
  | "students"
  | "assessments"
  | "preview";

type EditableCourse = Course & {
  overviewTitle: string;
  learningOutcomes: string[];
  objectives: string[];
  thumbnailUrl: string;
  weeklySchedule: any[];
  recentMaterials: any[];
};

const TAB_LABELS: { id: ActiveTab; label: string }[] = [
  { id: "overview", label: "Overview" },
  { id: "chapters", label: "Chapters" },
  { id: "materials", label: "Materials" },
  { id: "students", label: "Students" },
  { id: "assessments", label: "Assessments" },
  { id: "preview", label: "Preview" },
];

// IDs are now generated by the backend — no local counter needed.

const toNumber = (value: string, fallback: number) => {
  const parsed = Number(value.replace(/[^0-9]/g, ""));
  return Number.isInteger(parsed) && parsed > 0 ? parsed : fallback;
};

const initials = (name: string) =>
  name
    .split(" ")
    .filter(Boolean)
    .slice(0, 2)
    .map((part) => part[0]?.toUpperCase() ?? "")
    .join("");

const mapStudent = (student: BackendStudent, index: number): Student => ({
  id: toNumber(student.admissionNo, index + 1),
  backendId: student.id,
  name: student.name,
  email: student.email,
  grade: student.grade,
  avatar: initials(student.name),
  gender: "",
  dob: "",
  phone: "",
  guardian: student.guardian,
  guardianPhone: student.guardianPhone,
  address: "",
  enrollDate: "",
  status: student.status,
  attendance: { present: 0, absent: 0, late: 0, total: 0 },
  tests: [],
  progress: [],
  assignments: [],
  behavior: [],
  fees: { total: 0, paid: 0, pending: 0, status: "Pending" },
});

const mapClass = (classItem: BackendClass, teacher: Teacher, index: number): Course => ({
  id: toNumber(classItem.id, index + 1),
  name: classItem.name,
  code: `CLS-${classItem.name.replace(/\s+/g, "")}`,
  teacher: teacher.name,
  teacherId: teacher.id,
  description:
    classItem.subjects.length > 0
      ? `Configured subjects: ${classItem.subjects.map(s => s.name).join(", ")}`
      : "Configured class from backend.",
  schedule: classItem.academicYear,
  room: classItem.name,
  credits: classItem.subjects.length,
  progress: 0,
  chapters: [],
  materials: [],
  assignments: [],
  pastPapers: [],
});

const formatSlot = (slot: BackendTimetableSlot) => {
  const date = new Date(slot.date);
  const label = Number.isNaN(date.getTime())
    ? slot.date
    : date.toLocaleDateString(undefined, {
        weekday: "short",
        month: "short",
        day: "numeric",
      });
  return `${label} · ${slot.startTime} - ${slot.endTime}`;
};

const TeacherClasses = ({
  teacher,
  selectedClass,
  onSelectClass,
  onNavigate,
  allClasses = [],
}: Props) => {
  const queryClient = useQueryClient();
  const { data: teacherData, isLoading: loading } = useTeacherData(teacher);

  const classes = teacherData?.classes ?? [];
  const backendCourses = teacherData?.backendCourses ?? [];
  const students = teacherData?.students ?? [];
  const assignments = teacherData?.assignments ?? [];
  const quizzes = teacherData?.quizzes ?? [];
  const assignmentSubmissions = teacherData?.assignmentSubmissions ?? [];
  const quizSubmissions = teacherData?.quizSubmissions ?? [];
  const timetableSlots = teacherData?.timetableSlots ?? [];
  const gradebookEntries = teacherData?.gradebookEntries ?? [];

  const [activeTab, setActiveTab] = useState<ActiveTab>("overview");
  const [expandedStudentId, setExpandedStudentId] = useState<number | null>(null);
  const [expandedChapters, setExpandedChapters] = useState<Set<number>>(new Set());
  const [expandedTopics, setExpandedTopics] = useState<Set<number>>(new Set());

  const [backendCourseId, setBackendCourseId] = useState<string | null>(null);
  const [localCourse, setLocalCourse] = useState<EditableCourse | null>(null);
  const [isSaving, setIsSaving] = useState(false);
  const [currentClassId, setCurrentClassId] = useState<string | null>(null);

  // Overview tab drafts (persist across tab switches)
  const [titleDraft, setTitleDraft] = useState("");
  const [overviewDraft, setOverviewDraft] = useState("");
  const [outcomesDraft, setOutcomesDraft] = useState("");
  const [objectivesDraft, setObjectivesDraft] = useState("");
  const [thumbnailDraft, setThumbnailDraft] = useState("");
  const [thumbnailPublicId, setThumbnailPublicId] = useState<string | null>(null);
  const [thumbnailUploading, setThumbnailUploading] = useState(false);
  const [overviewLastSavedAt, setOverviewLastSavedAt] = useState<string | null>(null);
  const [weeklySchedule, setWeeklySchedule] = useState<any[]>([]);
  const [recentMaterials, setRecentMaterials] = useState<any[]>([]);
  const [materialTitle, setMaterialTitle] = useState("");
  const [materialUrl, setMaterialUrl] = useState("");
  const [materialContent, setMaterialContent] = useState("");
  const [materialFile, setMaterialFile] = useState<File | null>(null);



  const myCourses = classes;

  const classNameMap = useMemo(() => {
    const map: Record<string, string> = {};
    allClasses.forEach((cls) => {
      map[cls.id] = cls.name;
    });
    return map;
  }, [allClasses]);

  const selectedCourse = useMemo(() => {
    if (!selectedClass) return null;
    return myCourses.find((course) => course.name === selectedClass.name) ?? selectedClass;
  }, [myCourses, selectedClass]);

  // Sync localCourse when a class is selected, and auto-create the backend
  // course document if one does not exist yet (so students can see it immediately
  // via the grade-based fallback in GET /courses/student/enrolled).
  useEffect(() => {
    if (!selectedCourse) {
      setLocalCourse(null);
      setBackendCourseId(null);
      setCurrentClassId(null);
      return;
    }

    const matchingByClass = backendCourses.filter(
      (bc) => bc.grade === selectedCourse.backendId || bc.name === selectedCourse.name || bc.grade === selectedCourse.name,
    );
    const backendCourse =
      matchingByClass.find((bc) => bc.teacherId === teacher.backendId) ??
      matchingByClass[0];

    const newLocalCourse: EditableCourse = {
      ...selectedCourse,
      description: backendCourse?.description ?? selectedCourse.description,
      chapters: (backendCourse?.chapters ?? selectedCourse.chapters ?? []) as Course["chapters"],
      materials: (backendCourse?.materials ?? selectedCourse.materials ?? []) as Course["materials"],
      overviewTitle: backendCourse?.overviewTitle ?? selectedCourse.name,
      learningOutcomes: backendCourse?.learningOutcomes ?? [],
      objectives: backendCourse?.objectives ?? [],
      thumbnailUrl: backendCourse?.thumbnailUrl ?? "",
      weeklySchedule: backendCourse?.weeklySchedule ?? [],
      recentMaterials: backendCourse?.recentMaterials ?? backendCourse?.materials ?? [],
    };

    // Check if class actually changed (by ID/name) or if this is just a data update
    const classIdentifier = selectedCourse.name;
    const classChanged = currentClassId !== classIdentifier;

    setLocalCourse(newLocalCourse);
    setCurrentClassId(classIdentifier);

    // If backend data arrives after initial local render, hydrate untouched drafts.
    const draftsLookUntouched =
      titleDraft === (selectedCourse.name || "") &&
      overviewDraft === (selectedCourse.description || "") &&
      outcomesDraft.trim().length === 0 &&
      objectivesDraft.trim().length === 0 &&
      thumbnailDraft.trim().length === 0 &&
      weeklySchedule.length === 0 &&
      recentMaterials.length === 0;

    if (!classChanged && backendCourse && draftsLookUntouched) {
      setTitleDraft(newLocalCourse.overviewTitle || "");
      setOverviewDraft(newLocalCourse.description || "");
      setOutcomesDraft((newLocalCourse.learningOutcomes ?? []).join("\n"));
      setObjectivesDraft((newLocalCourse.objectives ?? []).join("\n"));
      setThumbnailDraft(newLocalCourse.thumbnailUrl || "");
      setThumbnailPublicId(backendCourse.thumbnailPublicId || null);
      setWeeklySchedule(newLocalCourse.weeklySchedule ?? []);
      setRecentMaterials(newLocalCourse.recentMaterials ?? backendCourse?.materials ?? []);
    }
    
    // Only reset UI states on actual class change, not on data updates
    if (classChanged) {
      setActiveTab("overview");
      setExpandedChapters(new Set());
      setExpandedTopics(new Set());
      setExpandedStudentId(null);
      setTitleDraft(newLocalCourse.overviewTitle || "");
      setOverviewDraft(newLocalCourse.description || "");
      setOutcomesDraft((newLocalCourse.learningOutcomes ?? []).join("\n"));
      setObjectivesDraft((newLocalCourse.objectives ?? []).join("\n"));
      setThumbnailDraft(newLocalCourse.thumbnailUrl || "");
      setThumbnailPublicId(backendCourse?.thumbnailPublicId || null);
      setOverviewLastSavedAt(backendCourse?.updatedAt || null);
      setWeeklySchedule(newLocalCourse.weeklySchedule ?? []);
      setRecentMaterials(newLocalCourse.recentMaterials ?? backendCourse?.materials ?? []);
      setMaterialTitle("");
      setMaterialUrl("");
      setMaterialContent("");
      setMaterialFile(null);
    }

    if (backendCourse) {
      setBackendCourseId(backendCourse.id);
    } else if (teacher.backendId) {
      // Auto-create the course so students can find it via grade lookup.
      setBackendCourseId(null);
      void (async () => {
        try {
          const res = await apiAuthRequest<BackendCourse>("/courses", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              code: `${selectedCourse.name.replace(/\s+/g, "")}-${teacher.subject.replace(/\s+/g, "")}-${Date.now()}`,
              name: selectedCourse.name,
              grade: selectedCourse.backendId || selectedCourse.name,
              description: `Course for ${selectedCourse.name}`,
              overviewTitle: selectedCourse.name,
              learningOutcomes: [],
              objectives: [],
              thumbnailUrl: "",
              schedule: selectedCourse.schedule || "Not set",
              weeklySchedule: [],
              teacherId: teacher.backendId,
              chapters: [],
              materials: [],
            }),
          });
          setBackendCourseId(res.id);
          queryClient.invalidateQueries({
            queryKey: ["teacher-data", teacher.id],
          });
        } catch {
          // Non-fatal — teacher can still view the class; data will persist on first edit.
        }
      })();
    }
  // Only depend on selectedCourse.name to avoid resets on data updates
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedCourse?.name, backendCourses]);

  const activeClassName = selectedCourse?.name;

  const classStudents = useMemo(
    () => (selectedCourse?.backendId ? students.filter((s) => s.grade === selectedCourse.backendId) : (activeClassName ? students.filter((s) => s.grade === activeClassName) : [])),
    [selectedCourse?.backendId, activeClassName, students],
  );
  const classAssignments = useMemo(
    () => (selectedCourse?.backendId ? assignments.filter((a) => a.classGrade === selectedCourse.backendId) : (activeClassName ? assignments.filter((a) => a.classGrade === activeClassName) : [])),
    [selectedCourse?.backendId, activeClassName, assignments],
  );
  const classQuizzes = useMemo(
    () => (selectedCourse?.backendId ? quizzes.filter((q) => q.classGrade === selectedCourse.backendId) : (activeClassName ? quizzes.filter((q) => q.classGrade === activeClassName) : [])),
    [selectedCourse?.backendId, activeClassName, quizzes],
  );
  const classAssignmentSubmissions = useMemo(() => {
    const ids = new Set(classAssignments.map((assignment) => assignment.id));
    return assignmentSubmissions.filter((submission) => ids.has(submission.assignmentId));
  }, [assignmentSubmissions, classAssignments]);
  const classQuizSubmissions = useMemo(() => {
    const ids = new Set(classQuizzes.map((quiz) => quiz.id));
    return quizSubmissions.filter((submission) => ids.has(submission.quizId));
  }, [quizSubmissions, classQuizzes]);
  const classTimetable = useMemo(
    () => (selectedCourse?.backendId ? timetableSlots.filter((s) => s.className === selectedCourse.backendId) : (activeClassName ? timetableSlots.filter((s) => s.className === activeClassName) : [])),
    [selectedCourse?.backendId, activeClassName, timetableSlots],
  );
  const classGradebook = useMemo(
    () => (selectedCourse?.backendId ? gradebookEntries.filter((e) => e.classGrade === selectedCourse.backendId) : (activeClassName ? gradebookEntries.filter((e) => e.classGrade === activeClassName) : [])),
    [selectedCourse?.backendId, activeClassName, gradebookEntries],
  );

  const formatAssessmentAverage = () => {
    if (!activeClassName || classGradebook.length === 0) return "0";
    const totals = classGradebook.flatMap((entry) =>
      entry.marks.map((mark) => (entry.totalMarks > 0 ? (mark.marks / entry.totalMarks) * 100 : 0)),
    );
    const average = totals.reduce((sum, value) => sum + value, 0) / totals.length;
    return average.toFixed(0);
  };

  // ---------------------------------------------------------------------------
  // Ensure a backend course document exists before any granular API call.
  // Returns the courseId (creates the course if backendCourseId is still null).
  // ---------------------------------------------------------------------------
  const createCourseMutation = useMutation({
    mutationFn: async (payload: any) => {
      return apiAuthRequest<BackendCourse>("/courses", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });
    },
    onSuccess: (res) => {
      setBackendCourseId(res.id);
      queryClient.setQueryData(["teacher-data", teacher.id], (old: any) => {
        if (!old) return old;
        return {
          ...old,
          backendCourses: [...old.backendCourses, res],
        };
      });
    },
  });

  const updateCourseMutation = useMutation({
    mutationFn: async ({
      courseId,
      path,
      method,
      payload,
      skipSync,
    }: {
      courseId: string;
      path: string;
      method: string;
      payload: any;
      skipSync?: boolean;
    }) => {
      return apiAuthRequest<BackendCourse>(`/courses/${courseId}${path}`, {
        method,
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });
    },
    onSuccess: (res, variables) => {
      if (variables.skipSync) return;
      syncFromResponse(res);
      queryClient.setQueryData(["teacher-data", teacher.id], (old: any) => {
        if (!old) return old;
        return {
          ...old,
          backendCourses: old.backendCourses.map((bc: any) =>
            bc.id === res.id ? res : bc,
          ),
        };
      });
    },
  });

  const ensureCourseId = async (): Promise<string | null> => {
    if (backendCourseId) return backendCourseId;
    if (!localCourse || !teacher.backendId) return null;

    try {
      const res = await createCourseMutation.mutateAsync({
        code: `${localCourse.name.replace(/\s+/g, "")}-${teacher.subject.replace(/\s+/g, "")}-${Date.now()}`,
        name: localCourse.name,
        grade: localCourse.name,
        description: localCourse.description || `Course for ${localCourse.name}`,
        overviewTitle: localCourse.overviewTitle || localCourse.name,
        learningOutcomes: localCourse.learningOutcomes ?? [],
        objectives: localCourse.objectives ?? [],
        thumbnailUrl: localCourse.thumbnailUrl ?? "",
        schedule: localCourse.schedule || "Not set",
        weeklySchedule: localCourse.weeklySchedule ?? [],
        teacherId: teacher.backendId,
        chapters: [],
        materials: [],
      });
      return res.id;
    } catch {
      toast.error("Could not save — failed to initialise course.");
      return null;
    }
  };

  // Sync localCourse from a fresh backend course response.
  const syncFromResponse = (res: BackendCourse) => {
    setLocalCourse((prev) =>
      prev
        ? {
            ...prev,
            chapters: (res.chapters ?? []) as Course["chapters"],
            materials: (res.materials ?? []) as Course["materials"],
            overviewTitle: res.overviewTitle ?? prev.overviewTitle,
            description: res.description ?? prev.description,
            learningOutcomes: res.learningOutcomes ?? prev.learningOutcomes,
            objectives: res.objectives ?? prev.objectives,
            thumbnailUrl: res.thumbnailUrl ?? prev.thumbnailUrl,
            weeklySchedule: res.weeklySchedule ?? prev.weeklySchedule,
              recentMaterials: (res as any).recentMaterials ?? res.materials ?? prev.recentMaterials,
          }
        : prev,
    );
  };

  // ---------------------------------------------------------------------------
  // Overview
  // ---------------------------------------------------------------------------
  const handleSaveOverview = async (payload: {
    title: string;
    description: string;
    learningOutcomes: string[];
    objectives: string[];
    thumbnailUrl?: string;
    thumbnailPublicId?: string | null;
    weeklySchedule: Array<{
      id?: string;
      day: string;
      startTime: string;
      endTime: string;
      topic?: string;
      location?: string;
    }>;
    recentMaterials?: any[];
  }) => {
    // Optimistic update.
    setLocalCourse((prev) =>
      prev
        ? {
            ...prev,
            overviewTitle: payload.title,
            description: payload.description,
            learningOutcomes: payload.learningOutcomes,
            objectives: payload.objectives,
            thumbnailUrl: payload.thumbnailUrl,
            weeklySchedule: payload.weeklySchedule,
            recentMaterials: payload.recentMaterials ?? [],
          }
        : prev,
    );
    setIsSaving(true);
    try {
      const courseId = await ensureCourseId();
      if (!courseId) return;
      await updateCourseMutation.mutateAsync({
        courseId,
        path: "/overview",
        method: "PATCH",
        payload,
      });
      setOverviewLastSavedAt(new Date().toISOString());
      toast.success("Overview saved.");
    } catch {
      toast.error("Failed to save overview.");
    } finally {
      setIsSaving(false);
    }
  };

  // ---------------------------------------------------------------------------
  // Course-level materials
  // ---------------------------------------------------------------------------
  const handleAddMaterial = async (material: Omit<StudyMaterial, "id">) => {
    setIsSaving(true);
    try {
      const courseId = await ensureCourseId();
      if (!courseId) return;
      await updateCourseMutation.mutateAsync({
        courseId,
        path: "/materials",
        method: "POST",
        payload: material,
      });
      toast.success("Material added.");
    } catch {
      toast.error("Failed to add material.");
    } finally {
      setIsSaving(false);
    }
  };

  const handleRemoveMaterial = async (materialId: string) => {
    setIsSaving(true);
    try {
      const courseId = await ensureCourseId();
      if (!courseId) return;
      await updateCourseMutation.mutateAsync({
        courseId,
        path: `/materials/${String(materialId)}`,
        method: "DELETE",
        payload: {},
      });
      toast.success("Material removed.");
    } catch {
      toast.error("Failed to remove material.");
    } finally {
      setIsSaving(false);
    }
  };

  // ---------------------------------------------------------------------------
  // Chapters
  // ---------------------------------------------------------------------------
  const handleAddChapter = async (data: {
    chapterNumber: number;
    chapterName: string;
    description?: string;
  }) => {
    setIsSaving(true);
    try {
      const courseId = await ensureCourseId();
      if (!courseId) return;
      await updateCourseMutation.mutateAsync({
        courseId,
        path: "/chapters",
        method: "POST",
        payload: data,
      });
      toast.success("Chapter added.");
    } catch {
      toast.error("Failed to add chapter.");
    } finally {
      setIsSaving(false);
    }
  };

  const handleUpdateChapter = async (
    chapterId: number | string,
    patch: {
      chapterNumber?: number;
      chapterName?: string;
      description?: string;
    },
  ) => {
    const courseId = backendCourseId;
    if (!courseId) return;
    // Optimistic.
    setLocalCourse((prev) =>
      prev
        ? {
            ...prev,
            chapters: (prev.chapters ?? []).map((ch) =>
              ch.id === chapterId ? { ...ch, ...patch } : ch,
            ),
          }
        : prev,
    );
    try {
      await updateCourseMutation.mutateAsync({
        courseId,
        path: `/chapters/${String(chapterId)}`,
        method: "PATCH",
        payload: patch,
        skipSync: true,
      });
    } catch {
      toast.error("Failed to update chapter.");
    }
  };
  const handleAddChapterMaterial = async (
    chapterId: number | string,
    material: Omit<StudyMaterial, "id">,
  ) => {
    setIsSaving(true);
    try {
      const courseId = await ensureCourseId();
      if (!courseId) return;
      await updateCourseMutation.mutateAsync({
        courseId,
        path: "/materials",
        method: "POST",
        payload: { ...material, chapterId: String(chapterId) },
      });
      toast.success("Chapter material added.");
    } catch {
      toast.error("Failed to add chapter material.");
    } finally {
      setIsSaving(false);
    }
  };

  // ---------------------------------------------------------------------------
  // Topics
  // ---------------------------------------------------------------------------
  const handleAddTopic = async (
    chapterId: number | string,
    topicName: string,
  ) => {
    setIsSaving(true);
    try {
      const courseId = await ensureCourseId();
      if (!courseId) return;
      await updateCourseMutation.mutateAsync({
        courseId,
        path: `/chapters/${String(chapterId)}/topics`,
        method: "POST",
        payload: { topicName },
      });
      toast.success("Topic added.");
    } catch {
      toast.error("Failed to add topic.");
    } finally {
      setIsSaving(false);
    }
  };

  const handleUpdateTopic = async (
    chapterId: number | string,
    topicId: number | string,
    topicName: string,
  ) => {
    const courseId = backendCourseId;
    if (!courseId) return;
    // Optimistic.
    setLocalCourse((prev) =>
      prev
        ? {
            ...prev,
            chapters: (prev.chapters ?? []).map((ch) =>
              ch.id === chapterId
                ? {
                    ...ch,
                    topics: (ch.topics ?? []).map((t) =>
                      t.id === topicId ? { ...t, topicName } : t,
                    ),
                  }
                : ch,
            ),
          }
        : prev,
    );
    try {
      await updateCourseMutation.mutateAsync({
        courseId,
        path: `/chapters/${String(chapterId)}/topics/${String(topicId)}`,
        method: "PATCH",
        payload: { topicName },
        skipSync: true,
      });
    } catch {
      toast.error("Failed to update topic.");
    }
  };

  const handleAddTopicMaterial = async (
    chapterId: number | string,
    topicId: number | string,
    material: Omit<StudyMaterial, "id">,
  ) => {
    setIsSaving(true);
    try {
      const courseId = await ensureCourseId();
      if (!courseId) return;
      await updateCourseMutation.mutateAsync({
        courseId,
        path: "/materials",
        method: "POST",
        payload: {
          ...material,
          chapterId: String(chapterId),
          topicId: String(topicId),
        },
      });
      toast.success("Topic material added.");
    } catch {
      toast.error("Failed to add topic material.");
    } finally {
      setIsSaving(false);
    }
  };

  const handleDeleteChapter = async (chapterId: number | string) => {
    const courseId = backendCourseId;
    if (!courseId) return;
    if (!confirm("Are you sure you want to delete this chapter and all its topics?")) return;

    setIsSaving(true);
    try {
      await updateCourseMutation.mutateAsync({
        courseId,
        path: `/chapters/${String(chapterId)}`,
        method: "DELETE",
        payload: {},
      });
      toast.success("Chapter deleted.");
    } catch {
      toast.error("Failed to delete chapter.");
    } finally {
      setIsSaving(false);
    }
  };

  const handleDeleteTopic = async (chapterId: number | string, topicId: number | string) => {
    const courseId = backendCourseId;
    if (!courseId) return;
    if (!confirm("Are you sure you want to delete this topic?")) return;

    setIsSaving(true);
    try {
      await updateCourseMutation.mutateAsync({
        courseId,
        path: `/chapters/${String(chapterId)}/topics/${String(topicId)}`,
        method: "DELETE",
        payload: {},
      });
      toast.success("Topic deleted.");
    } catch {
      toast.error("Failed to delete topic.");
    } finally {
      setIsSaving(false);
    }
  };

  const handleSelectClass = (course: Course) => {
    onSelectClass(course);
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center py-16 text-muted-foreground gap-2">
        <span className="spinner h-4 w-4" />
        Loading classes...
      </div>
    );
  }

  if (localCourse) {
    return (
      <div className="space-y-6 max-w-7xl mx-auto px-4 sm:px-6 py-6">
        <button
          onClick={() => onSelectClass(null)}
          className="inline-flex items-center gap-2 text-sm font-medium text-muted-foreground hover:text-foreground transition-all group"
        >
          <ArrowLeft className="h-4 w-4 transition-transform group-hover:-translate-x-1" />
          Back to Classes
        </button>

        {/* Class header */}
        <div className="rounded-2xl bg-card border border-border/60 shadow-sm hover:shadow-md transition-all duration-300 p-6 md:p-8">
          <div className="flex flex-col lg:flex-row lg:items-start lg:justify-between gap-6">
            <div className="space-y-3">
              <h1 className="text-3xl font-bold tracking-tight text-foreground">
                {classNameMap[localCourse.backendId] || localCourse.name}
              </h1>
              <div className="flex flex-wrap items-center gap-x-4 gap-y-2 text-sm text-muted-foreground">
                <span className="font-mono">{localCourse.code}</span>
                <span className="hidden sm:inline">•</span>
                <span>{localCourse.room}</span>
                <span className="hidden sm:inline">•</span>
                <span className="flex items-center gap-1">
                  <Clock className="h-3.5 w-3.5" />
                  {localCourse.schedule}
                </span>
              </div>
              <p className="text-sm text-muted-foreground max-w-2xl leading-relaxed">
                {localCourse.description}
              </p>
            </div>

            <div className="flex flex-wrap gap-4">
              {[
                { label: "Students", value: classStudents.length, icon: Users },
                { label: "Assessments", value: classGradebook.length, icon: BookOpen },
                { label: "Avg Score", value: `${formatAssessmentAverage()}%`, icon: TrendingUp },
              ].map((stat) => (
                <div key={stat.label} className="group relative rounded-xl bg-muted/30 p-4 min-w-[110px] text-center hover:bg-muted/40 transition-all">
                  <div className="h-10 w-10 rounded-full bg-primary/10 text-primary flex items-center justify-center mx-auto mb-2">
                    <stat.icon className="h-5 w-5" />
                  </div>
                  <p className="text-xl font-bold text-foreground">{stat.value}</p>
                  <p className="text-xs text-muted-foreground uppercase tracking-wide">{stat.label}</p>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Tabs */}
        <div className="flex flex-wrap gap-1 border-b border-border/60 pb-2">
          {TAB_LABELS.map(({ id, label }) => (
            <button
              key={id}
              onClick={() => setActiveTab(id)}
              className={`px-5 py-2.5 text-sm font-medium rounded-lg transition-all ${
                activeTab === id
                  ? "bg-primary/10 text-primary shadow-sm"
                  : "text-muted-foreground hover:text-foreground hover:bg-muted/30"
              }`}
            >
              {label}
            </button>
          ))}
        </div>

        {/* Tab content */}
        <div className="rounded-2xl bg-card border border-border/60 shadow-sm p-6">
          {activeTab === "overview" && (
            <OverviewTab
              selectedClass={localCourse}
              onSaveOverview={handleSaveOverview}
              onAddMaterial={handleAddMaterial}
              onDeleteMaterial={handleRemoveMaterial}
              titleDraft={titleDraft}
              setTitleDraft={setTitleDraft}
              overviewDraft={overviewDraft}
              setOverviewDraft={setOverviewDraft}
              outcomesDraft={outcomesDraft}
              setOutcomesDraft={setOutcomesDraft}
              objectivesDraft={objectivesDraft}
              setObjectivesDraft={setObjectivesDraft}
              thumbnailDraft={thumbnailDraft}
              setThumbnailDraft={setThumbnailDraft}
              thumbnailPublicId={thumbnailPublicId}
              setThumbnailPublicId={setThumbnailPublicId}
              thumbnailUploading={thumbnailUploading}
              setThumbnailUploading={setThumbnailUploading}
              overviewLastSavedAt={overviewLastSavedAt}
              weeklySchedule={weeklySchedule}
              setWeeklySchedule={setWeeklySchedule}
              recentMaterials={recentMaterials}
              setRecentMaterials={setRecentMaterials}
              materialTitle={materialTitle}
              setMaterialTitle={setMaterialTitle}
              materialUrl={materialUrl}
              setMaterialUrl={setMaterialUrl}
              materialContent={materialContent}
              setMaterialContent={setMaterialContent}
              materialFile={materialFile}
              setMaterialFile={setMaterialFile}
            />
          )}

          {activeTab === "chapters" && (
            <ChaptersTab
              selectedClass={localCourse}
              expandedChapters={expandedChapters}
              expandedTopics={expandedTopics}
              onToggleChapter={(id) =>
                setExpandedChapters((prev) => {
                  const next = new Set(prev);
                  if (next.has(id)) {
                    next.delete(id);
                  } else {
                    next.add(id);
                  }
                  return next;
                })
              }
              onToggleTopic={(id) =>
                setExpandedTopics((prev) => {
                  const next = new Set(prev);
                  if (next.has(id)) {
                    next.delete(id);
                  } else {
                    next.add(id);
                  }
                  return next;
                })
              }
              onAddChapter={handleAddChapter}
              onUpdateChapter={handleUpdateChapter}
              onDeleteChapter={handleDeleteChapter}
              onAddChapterMaterial={handleAddChapterMaterial}
              onAddTopic={handleAddTopic}
              onUpdateTopic={handleUpdateTopic}
              onDeleteTopic={handleDeleteTopic}
              onAddTopicMaterial={handleAddTopicMaterial}
            />
          )}

          {activeTab === "materials" && (
            <MaterialsTab selectedClass={localCourse} />
          )}

          {activeTab === "students" && (
            <StudentsSection
              classStudents={classStudents}
              teacher={teacher}
              expandedStudentId={expandedStudentId}
              onToggleStudent={(id) =>
                setExpandedStudentId((prev) => (prev === id ? null : id))
              }
            />
          )}

          {activeTab === "assessments" && (
            <div className="space-y-8">
              <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                <div className="rounded-xl border border-border/60 bg-muted/15 p-4">
                  <p className="text-xs text-muted-foreground">Assignment Submissions</p>
                  <p className="text-xl font-bold text-foreground mt-1">
                    {classAssignmentSubmissions.length}/{Math.max(classAssignments.length * Math.max(classStudents.length, 1), 1)}
                  </p>
                </div>
                <div className="rounded-xl border border-border/60 bg-muted/15 p-4">
                  <p className="text-xs text-muted-foreground">Quiz Attempts</p>
                  <p className="text-xl font-bold text-foreground mt-1">
                    {classQuizSubmissions.length}/{Math.max(classQuizzes.length * Math.max(classStudents.length, 1), 1)}
                  </p>
                </div>
                <div className="rounded-xl border border-border/60 bg-muted/15 p-4">
                  <p className="text-xs text-muted-foreground">Overall Performance</p>
                  <p className="text-xl font-bold text-foreground mt-1">{formatAssessmentAverage()}%</p>
                </div>
              </div>

              <div className="flex flex-wrap gap-2">
                <button
                  onClick={() => onNavigate("assignments")}
                  className="inline-flex items-center gap-2 rounded-lg border border-primary px-3 py-2 text-sm text-primary hover:bg-primary/10"
                >
                  Manage Assignments
                </button>
                <button
                  onClick={() => onNavigate("checkQuizzes")}
                  className="inline-flex items-center gap-2 rounded-lg border border-primary px-3 py-2 text-sm text-primary hover:bg-primary/10"
                >
                  Manage Quiz Results
                </button>
              </div>

              {/* Assignments */}
              <div>
                <h3 className="text-lg font-semibold text-foreground mb-4 flex items-center gap-2">
                  <BookOpen className="h-5 w-5 text-primary" /> Assignments
                </h3>
                {classAssignments.length === 0 ? (
                  <p className="text-sm text-muted-foreground bg-muted/20 rounded-xl p-4 text-center">No assignments found for this class.</p>
                ) : (
                  <div className="space-y-3">
                    {classAssignments.map((assignment) => (
                      <div key={assignment.id} className="rounded-xl border border-border/60 p-4 hover:border-primary/30 transition-all">
                        <div className="flex items-start justify-between gap-4">
                          <div>
                            <p className="font-semibold text-foreground">{assignment.title}</p>
                            <p className="text-xs text-muted-foreground mt-1">
                              {assignment.subject} · Due {new Date(assignment.dueDate).toLocaleDateString()}
                            </p>
                            {assignment.description && (
                              <p className="text-sm text-muted-foreground mt-2 line-clamp-2">{assignment.description}</p>
                            )}
                          </div>
                          <span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-medium text-primary">
                            {assignment.totalMarks} marks
                          </span>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* Quizzes */}
              <div>
                <h3 className="text-lg font-semibold text-foreground mb-4 flex items-center gap-2">
                  <BookOpen className="h-5 w-5 text-primary" /> Quizzes
                </h3>
                {classQuizzes.length === 0 ? (
                  <p className="text-sm text-muted-foreground bg-muted/20 rounded-xl p-4 text-center">No quizzes found for this class.</p>
                ) : (
                  <div className="space-y-3">
                    {classQuizzes.map((quiz) => (
                      <div key={quiz.id} className="rounded-xl border border-border/60 p-4 hover:border-primary/30 transition-all">
                        <p className="font-semibold text-foreground">{quiz.title}</p>
                        <p className="text-xs text-muted-foreground mt-1">
                          {quiz.subject}
                          {quiz.chapterName ? ` · ${quiz.chapterName}` : ""}
                          {quiz.topicName ? ` · ${quiz.topicName}` : ""}
                        </p>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* Timetable */}
              <div>
                <h3 className="text-lg font-semibold text-foreground mb-4 flex items-center gap-2">
                  <Clock className="h-5 w-5 text-primary" /> Timetable
                </h3>
                {classTimetable.length === 0 ? (
                  <p className="text-sm text-muted-foreground bg-muted/20 rounded-xl p-4 text-center">No timetable slots found for this class.</p>
                ) : (
                  <div className="space-y-3">
                    {classTimetable.map((slot) => (
                      <div key={slot.id} className="rounded-xl border border-border/60 p-4 flex items-center justify-between gap-4 hover:border-primary/30 transition-all">
                        <div>
                          <p className="font-semibold text-foreground">{slot.subject}</p>
                          <p className="text-xs text-muted-foreground mt-1">{formatSlot(slot)}</p>
                        </div>
                        <span className="rounded-full bg-muted/30 px-3 py-1 text-xs text-muted-foreground">
                          {slot.teacherName}
                        </span>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </div>
          )}

          {activeTab === "preview" && (
            <PreviewTab
              selectedClass={localCourse}
              studentCount={classStudents.length}
            />
          )}
        </div>
      </div>
    );
  }

  // Class list view
  return (
    <div className="space-y-8 animate-fade-in max-w-7xl mx-auto px-4 sm:px-6 py-6">
      <div className="text-center sm:text-left">
        <h1 className="text-2xl sm:text-3xl font-bold tracking-tight text-foreground flex items-center justify-center sm:justify-start gap-2">
          <BookOpen className="h-7 w-7 text-primary" /> My Classes
        </h1>
        <p className="text-sm text-muted-foreground mt-1">
          Live backend classes assigned to {teacher.name}.
        </p>
      </div>

      {myCourses.length === 0 ? (
        <div className="rounded-2xl bg-card border border-dashed border-border p-8 text-center text-muted-foreground">
          <BookOpen className="h-12 w-12 mx-auto mb-3 text-muted-foreground/30" />
          <p>No backend classes are assigned to this teacher yet.</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {myCourses.map((course) => {
            const courseStudents = students.filter((s) => s.grade === course.name);
            const courseAssessments = gradebookEntries.filter((e) => e.classGrade === course.name);
            const courseSlots = timetableSlots.filter((s) => s.className === course.name);

            return (
              <button
                key={course.id}
                onClick={() => handleSelectClass(course)}
                className="group text-left overflow-hidden rounded-2xl bg-card border border-border/60 shadow-sm hover:shadow-md transition-all duration-300 hover:-translate-y-1 p-6 focus-visible:ring-2 focus-visible:ring-primary/30"
              >
                <div className="flex items-start justify-between mb-4">
                  <div>
                    <h3 className="text-xl font-semibold text-foreground group-hover:text-primary transition-colors">
                      {classNameMap[course.backendId] || course.name}
                    </h3>
                    <p className="text-sm text-muted-foreground font-mono mt-0.5">{course.code}</p>
                  </div>
                  <div className="h-10 w-10 rounded-xl bg-primary/10 flex items-center justify-center group-hover:bg-primary/20 transition-colors">
                    <BookOpen className="h-5 w-5 text-primary" />
                  </div>
                </div>

                <div className="space-y-2 text-sm text-muted-foreground">
                  <div className="flex items-center gap-2">
                    <span className="font-medium">Academic Year:</span> {course.schedule}
                  </div>
                  <div className="flex items-center gap-2">
                    <Clock className="h-4 w-4" />
                    {courseSlots.length > 0 ? formatSlot(courseSlots[0]) : "No timetable slots"}
                  </div>
                  <div className="flex items-center gap-2">
                    <Users className="h-4 w-4" />
                    {courseStudents.length} Students
                  </div>
                  <div className="flex items-center gap-2">
                    <TrendingUp className="h-4 w-4" />
                    {courseAssessments.length} Assessments
                  </div>
                </div>

                <div className="mt-5">
                  <div className="flex justify-between text-xs mb-1.5">
                    <span className="text-muted-foreground">Configured subjects</span>
                    <span className="font-medium text-foreground">{course.credits}</span>
                  </div>
                  <div className="h-1.5 bg-muted/50 rounded-full overflow-hidden">
                    <div className="h-full bg-primary rounded-full transition-all duration-300 group-hover:bg-primary/80" style={{ width: "100%" }} />
                  </div>
                </div>
              </button>
            );
          })}
        </div>
      )}
    </div>
  );
};

export default TeacherClasses;