import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, BookOpen, Clock, TrendingUp, Users } from "lucide-react";
import type { Course, Student, StudyMaterial, Teacher } from "@/types/domain";
import { toast } from "sonner";
import { apiAuthRequest } from "@/lib/api";
import { deleteFileFromCloudinary } from "@/lib/cloudinary-upload";
import { loadAuthSession } from "@/lib/auth";
import { ensureCourseByClassAndSubject } from "@/lib/course-api";
import { useMutation } from "@tanstack/react-query";
import { useTeacherData, type BackendCourse, type BackendClass, type BackendStudent, type BackendAssignment, type BackendQuiz, type AssignmentSubmission, type QuizSubmission, type BackendTimetableSlot, type BackendGradebookEntry, type BackendTeacherClassCourse } from "@/hooks/use-teacher-data";
import ChaptersTab from "./chapters/ChaptersTab";
import MaterialsTab from "./materials/MaterialsTab";
import OverviewTab from "./overview/OverviewTab";
import PreviewTab from "./preview/PreviewTab";
import StudentsSection from "./students/StudentsSection";

interface Props {
  teacher: Teacher;
  selectedClass: Course | null;
  onSelectClass: (course: Course | null) => void;
  onNavigate: (nav: string, options?: { assignmentId?: number; testId?: number }) => void;
  allClasses?: BackendClass[];
  classRouteId?: string;
  courseRouteId?: string;
  onOpenClassCourses?: (classId: string) => void;
  onOpenCourseMaterials?: (classId: string, courseId: string) => void;
  onBackToClasses?: () => void;
  onBackToClassCourses?: (classId: string) => void;
}

type ActiveTab =
  | "overview"
  | "chapters"
  | "materials"
  | "students"
  | "assessments"
  | "preview";

type EditableCourse = Course & {
  overviewTitle: string;
  learningOutcomes: string[];
  objectives: string[];
  thumbnailUrl: string;
  weeklySchedule: any[];
  recentMaterials: any[];
  overview?: Course["overview"];
};

const TAB_LABELS: { id: ActiveTab; label: string }[] = [
  { id: "overview", label: "Overview" },
  { id: "chapters", label: "Chapters" },
  { id: "materials", label: "Materials" },
  { id: "students", label: "Students" },
  { id: "assessments", label: "Assessments" },
  { id: "preview", label: "Preview" },
];

// IDs are now generated by the backend — no local counter needed.

const toNumber = (value: string, fallback: number) => {
  const parsed = Number(value.replace(/[^0-9]/g, ""));
  return Number.isInteger(parsed) && parsed > 0 ? parsed : fallback;
};

const initials = (name: string) =>
  name
    .split(" ")
    .filter(Boolean)
    .slice(0, 2)
    .map((part) => part[0]?.toUpperCase() ?? "")
    .join("");

const mapStudent = (student: BackendStudent, index: number): Student => ({
  id: toNumber(student.admissionNo, index + 1),
  backendId: student.id,
  name: student.name,
  email: student.email,
  grade: student.grade,
  avatar: initials(student.name),
  gender: "",
  dob: "",
  phone: "",
  guardian: student.guardian,
  guardianPhone: student.guardianPhone,
  address: "",
  enrollDate: "",
  status: student.status,
  attendance: { present: 0, absent: 0, late: 0, total: 0 },
  tests: [],
  progress: [],
  assignments: [],
  behavior: [],
  fees: { total: 0, paid: 0, pending: 0, status: "Pending" },
});

const mapClass = (classItem: BackendClass, teacher: Teacher, index: number): Course => ({
  id: toNumber(classItem.id, index + 1),
  name: classItem.name,
  code: `CLS-${classItem.name.replace(/\s+/g, "")}`,
  teacher: teacher.name,
  teacherId: teacher.id,
  description:
    classItem.subjects.length > 0
      ? `Configured subjects: ${classItem.subjects.map(s => s.name).join(", ")}`
      : "Configured class from backend.",
  schedule: classItem.academicYear,
  room: classItem.name,
  credits: classItem.subjects.length,
  progress: 0,
  chapters: [],
  materials: [],
  assignments: [],
  pastPapers: [],
});

const formatSlot = (slot: { date: string; startTime: string; endTime: string }) => {
  const date = new Date(slot.date);
  const label = Number.isNaN(date.getTime())
    ? slot.date
    : date.toLocaleDateString(undefined, {
        weekday: "short",
        month: "short",
        day: "numeric",
      });
  return `${label} · ${slot.startTime} - ${slot.endTime}`;
};

const TeacherClasses = ({
  teacher,
  selectedClass,
  onSelectClass,
  onNavigate,
  allClasses = [],
  classRouteId,
  courseRouteId,
  onOpenClassCourses,
  onOpenCourseMaterials,
  onBackToClasses,
  onBackToClassCourses,
}: Props) => {
  const { data: teacherData, isLoading: loading } = useTeacherData(teacher);

  const classes = teacherData?.classes ?? [];
  const classCourses = teacherData?.classCourses ?? [];
  const students = teacherData?.students ?? [];
  const assignments = teacherData?.assignments ?? [];
  const quizzes = teacherData?.quizzes ?? [];
  const assignmentSubmissions = teacherData?.assignmentSubmissions ?? [];
  const quizSubmissions = teacherData?.quizSubmissions ?? [];
  const timetableSlots = teacherData?.timetableSlots ?? [];
  const gradebookEntries = teacherData?.gradebookEntries ?? [];

  const [activeTab, setActiveTab] = useState<ActiveTab>("overview");
  const [expandedStudentId, setExpandedStudentId] = useState<number | null>(null);
  const [expandedChapters, setExpandedChapters] = useState<Set<number>>(new Set());
  const [expandedTopics, setExpandedTopics] = useState<Set<number>>(new Set());

  const [backendCourseId, setBackendCourseId] = useState<string | null>(null);
  const [localCourse, setLocalCourse] = useState<EditableCourse | null>(null);
  const [isSaving, setIsSaving] = useState(false);
  const [currentClassId, setCurrentClassId] = useState<string | null>(null);
  const [selectedCourseId, setSelectedCourseId] = useState<string | null>(null);

  // Overview tab drafts (persist across tab switches)
  const [titleDraft, setTitleDraft] = useState("");
  const [overviewDraft, setOverviewDraft] = useState("");
  const [outcomesDraft, setOutcomesDraft] = useState("");
  const [objectivesDraft, setObjectivesDraft] = useState("");
  const [thumbnailDraft, setThumbnailDraft] = useState("");
  const [thumbnailPublicId, setThumbnailPublicId] = useState<string | null>(null);
  const [thumbnailUploading, setThumbnailUploading] = useState(false);
  const [overviewLastSavedAt, setOverviewLastSavedAt] = useState<string | null>(null);
  const [weeklySchedule, setWeeklySchedule] = useState<any[]>([]);
  const [recentMaterials, setRecentMaterials] = useState<any[]>([]);
  const [materialTitle, setMaterialTitle] = useState("");
  const [materialUrl, setMaterialUrl] = useState("");
  const [materialContent, setMaterialContent] = useState("");
  const [materialFile, setMaterialFile] = useState<File | null>(null);

  const myClasses = useMemo(() => {
    const assignedClassIds = new Set((teacher.classes || []).map(String));
    return classes.filter((cls) => assignedClassIds.has(String(cls.backendId || cls.id)));
  }, [classes, teacher.classes]);

  const classNameMap = useMemo(() => {
    const map: Record<string, string> = {};
    allClasses.forEach((cls) => {
      map[cls.id] = cls.name;
    });
    return map;
  }, [allClasses]);

  const classCourseMap = useMemo(
    () => new Map(classCourses.map((entry) => [entry.classId, entry] as const)),
    [classCourses],
  );

  type TeacherAssignedCourse = BackendTeacherClassCourse["courses"][number];

  const routeSelectedClass = useMemo(() => {
    if (!classRouteId) return null;
    return (
      myClasses.find(
        (course) =>
          String(course.backendId || "") === classRouteId ||
          String(course.name || "") === classRouteId,
      ) ?? null
    );
  }, [classRouteId, myClasses]);

  const selectedClassCourses = useMemo(() => {
    if (!classRouteId) return null;
    return (
      classCourses.find(
        (entry) =>
          entry.classId === classRouteId || entry.className === classRouteId,
      ) ?? null
    );
  }, [classCourses, classRouteId]);

  const selectedCourseCourse = useMemo(() => {
    if (!selectedClassCourses || !courseRouteId) return null;
    return (
      selectedClassCourses.courses.find(
        (course) =>
          course.id === courseRouteId ||
          course.subjectId === courseRouteId,
      ) ?? null
    );
  }, [courseRouteId, selectedClassCourses]);

  const selectedCourse = useMemo(() => {
    const effective = routeSelectedClass ?? selectedClass;
    if (!effective) return null;
    return myClasses.find((course) => course.name === effective.name) ?? effective;
  }, [myClasses, routeSelectedClass, selectedClass]);

  const coursesForSelectedClass = useMemo<TeacherAssignedCourse[]>(() => {
    if (!selectedClassCourses) return [];

    return selectedClassCourses.courses;
  }, [selectedClassCourses]);

  // Sync localCourse when a class is selected.
  useEffect(() => {
    if (!selectedCourse) {
      setLocalCourse(null);
      setBackendCourseId(null);
      setCurrentClassId(null);
      return;
    }

    if (classRouteId && !courseRouteId) {
      setLocalCourse(null);
      setBackendCourseId(null);
      return;
    }

    const backendCourse = selectedCourseId
      ? coursesForSelectedClass.find(
          (bc) =>
            bc.id === selectedCourseId ||
            bc.subjectId === selectedCourseId ||
            bc.courseId === selectedCourseId,
        ) ?? null
      : courseRouteId
        ? coursesForSelectedClass.find(
            (bc) =>
              bc.id === courseRouteId ||
              bc.subjectId === courseRouteId ||
              bc.courseId === courseRouteId,
          ) ?? null
        : coursesForSelectedClass[0] ?? null;

    const newLocalCourse: EditableCourse = {
      ...selectedCourse,
      description: backendCourse?.description ?? selectedCourse.description,
      chapters: (backendCourse?.chapters ?? selectedCourse.chapters ?? []) as Course["chapters"],
      materials: (backendCourse?.materials ?? selectedCourse.materials ?? []) as Course["materials"],
      overviewTitle: backendCourse?.overviewTitle ?? selectedCourse.name,
      learningOutcomes: backendCourse?.learningOutcomes ?? [],
      objectives: backendCourse?.objectives ?? [],
      thumbnailUrl: backendCourse?.thumbnailUrl ?? "",
      weeklySchedule: backendCourse?.weeklySchedule ?? [],
      recentMaterials: backendCourse?.recentMaterials ?? backendCourse?.materials ?? [],
      overview: (backendCourse as any)?.overview ?? (selectedCourse as any).overview,
    };

    // Check if class actually changed (by ID/name) or if this is just a data update
    const classIdentifier = `${selectedCourse.name}::${backendCourse?.id ?? "class"}`;
    const classChanged = currentClassId !== classIdentifier;

    setLocalCourse(newLocalCourse);
    setCurrentClassId(classIdentifier);

    // If backend data arrives after initial local render, hydrate untouched drafts.
    const draftsLookUntouched =
      titleDraft === (selectedCourse.name || "") &&
      overviewDraft === (selectedCourse.description || "") &&
      outcomesDraft.trim().length === 0 &&
      objectivesDraft.trim().length === 0 &&
      thumbnailDraft.trim().length === 0 &&
      weeklySchedule.length === 0 &&
      recentMaterials.length === 0;

    if (!classChanged && backendCourse && draftsLookUntouched) {
      setTitleDraft(newLocalCourse.overviewTitle || "");
      setOverviewDraft(newLocalCourse.description || "");
      setOutcomesDraft((newLocalCourse.learningOutcomes ?? []).join("\n"));
      setObjectivesDraft((newLocalCourse.objectives ?? []).join("\n"));
      setThumbnailDraft(newLocalCourse.thumbnailUrl || "");
      setThumbnailPublicId(backendCourse.thumbnailPublicId || null);
      setWeeklySchedule(newLocalCourse.weeklySchedule ?? []);
      setRecentMaterials(newLocalCourse.recentMaterials ?? backendCourse?.materials ?? []);
    }
    
    // Only reset UI states on actual class change, not on data updates
    if (classChanged) {
      setActiveTab("overview");
      setExpandedChapters(new Set());
      setExpandedTopics(new Set());
      setExpandedStudentId(null);
      setTitleDraft(newLocalCourse.overviewTitle || "");
      setOverviewDraft(newLocalCourse.description || "");
      setOutcomesDraft((newLocalCourse.learningOutcomes ?? []).join("\n"));
      setObjectivesDraft((newLocalCourse.objectives ?? []).join("\n"));
      setThumbnailDraft(newLocalCourse.thumbnailUrl || "");
      setThumbnailPublicId(backendCourse?.thumbnailPublicId || null);
      setOverviewLastSavedAt(backendCourse?.updatedAt || null);
      setWeeklySchedule(newLocalCourse.weeklySchedule ?? []);
      setRecentMaterials(newLocalCourse.recentMaterials ?? backendCourse?.materials ?? []);
      setMaterialTitle("");
      setMaterialUrl("");
      setMaterialContent("");
      setMaterialFile(null);
    }

    if (classChanged) {
      setSelectedCourseId(backendCourse?.id ?? null);
    }

    setBackendCourseId((backendCourse as any)?.courseId ?? courseRouteId ?? backendCourse?.id ?? null);
  // Only depend on selectedCourse.name to avoid resets on data updates
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [classRouteId, courseRouteId, selectedCourse?.name, coursesForSelectedClass, selectedCourseId]);

  useEffect(() => {
    if (courseRouteId) {
      setSelectedCourseId(courseRouteId);
      setActiveTab("materials");
    }
  }, [courseRouteId]);

  const activeClassName = selectedCourse?.name;

  const classStudents = useMemo(
    () => (selectedCourse?.backendId ? students.filter((s) => s.grade === selectedCourse.backendId) : (activeClassName ? students.filter((s) => s.grade === activeClassName) : [])),
    [selectedCourse?.backendId, activeClassName, students],
  );
  const classAssignments = useMemo(
    () => (selectedCourse?.backendId ? assignments.filter((a) => a.classGrade === selectedCourse.backendId) : (activeClassName ? assignments.filter((a) => a.classGrade === activeClassName) : [])),
    [selectedCourse?.backendId, activeClassName, assignments],
  );
  const classQuizzes = useMemo(
    () => (selectedCourse?.backendId ? quizzes.filter((q) => q.classGrade === selectedCourse.backendId) : (activeClassName ? quizzes.filter((q) => q.classGrade === activeClassName) : [])),
    [selectedCourse?.backendId, activeClassName, quizzes],
  );
  const classAssignmentSubmissions = useMemo(() => {
    const ids = new Set(classAssignments.map((assignment) => assignment.id));
    return assignmentSubmissions.filter((submission) => ids.has(submission.assignmentId));
  }, [assignmentSubmissions, classAssignments]);
  const classQuizSubmissions = useMemo(() => {
    const ids = new Set(classQuizzes.map((quiz) => quiz.id));
    return quizSubmissions.filter((submission) => ids.has(submission.quizId));
  }, [quizSubmissions, classQuizzes]);
  const classTimetable = useMemo(
    () => (selectedCourse?.backendId ? timetableSlots.filter((s) => s.className === selectedCourse.backendId) : (activeClassName ? timetableSlots.filter((s) => s.className === activeClassName) : [])),
    [selectedCourse?.backendId, activeClassName, timetableSlots],
  );
  const classGradebook = useMemo(
    () => (selectedCourse?.backendId ? gradebookEntries.filter((e) => e.classGrade === selectedCourse.backendId) : (activeClassName ? gradebookEntries.filter((e) => e.classGrade === activeClassName) : [])),
    [selectedCourse?.backendId, activeClassName, gradebookEntries],
  );

  const formatAssessmentAverage = () => {
    if (!activeClassName || classGradebook.length === 0) return "0";
    const totals = classGradebook.flatMap((entry) =>
      entry.marks.map((mark) => (entry.totalMarks > 0 ? (mark.marks / entry.totalMarks) * 100 : 0)),
    );
    const average = totals.reduce((sum, value) => sum + value, 0) / totals.length;
    return average.toFixed(0);
  };

  const updateCourseMutation = useMutation({
    mutationFn: async ({
      courseId,
      path,
      method,
      payload,
      skipSync,
    }: {
      courseId: string;
      path: string;
      method: string;
      payload: any;
      skipSync?: boolean;
    }) => {
      return {
        id: courseId,
        name: selectedCourse?.name ?? "",
        code: selectedCourse?.code ?? "",
        grade: selectedCourse?.backendId ?? "",
        description: selectedCourse?.description ?? "",
        schedule: selectedCourse?.schedule ?? "",
        teacherId: teacher.backendId ?? "",
        chapters: localCourse?.chapters ?? [],
        materials: localCourse?.materials ?? [],
        recentMaterials: localCourse?.recentMaterials ?? [],
        weeklySchedule: localCourse?.weeklySchedule ?? [],
      } as BackendCourse;
    },
    onSuccess: (res, variables) => {
      if (variables.skipSync) return;
      syncFromResponse(res);
    },
  });

  const ensureCourseId = async (): Promise<string | null> => {
    // If we already have a cached backend course ID, return it
    if (backendCourseId) {
      return backendCourseId;
    }

    try {
      // Resolve classId and subjectId from component state
      const resolvedClassId = selectedCourse?.backendId ?? classRouteId;
      const resolvedSubjectId = selectedCourseCourse?.subjectId ?? courseRouteId;

      if (!resolvedClassId || !resolvedSubjectId) {
        toast.error("Missing class or subject id for course ensure.");
        return null;
      }

      // Call ensure endpoint to get/create persistent course document
      const ensuredCourse = await ensureCourseByClassAndSubject(
        resolvedClassId,
        resolvedSubjectId,
        selectedClass?.name || "Course"
      );

      if (!ensuredCourse?.id) {
        toast.error("Failed to ensure course.");
        return null;
      }

      // Cache the persistent MongoDB course ID
      setBackendCourseId(ensuredCourse.id);
      return ensuredCourse.id;
    } catch (error) {
      console.error("[TeacherClasses] Failed to ensure course:", error);
      toast.error("Failed to ensure course.");
      return null;
    }
  };

  // Sync localCourse from a fresh backend course response.
  const syncFromResponse = (res: BackendCourse) => {
    setLocalCourse((prev) =>
      prev
        ? {
            ...prev,
            chapters: (res.chapters ?? []) as Course["chapters"],
            materials: (res.materials ?? []) as Course["materials"],
            overviewTitle: res.overviewTitle ?? prev.overviewTitle,
            description: res.description ?? prev.description,
            learningOutcomes: res.learningOutcomes ?? prev.learningOutcomes,
            objectives: res.objectives ?? prev.objectives,
            thumbnailUrl: res.thumbnailUrl ?? prev.thumbnailUrl,
            weeklySchedule: res.weeklySchedule ?? prev.weeklySchedule,
            recentMaterials: (res as any).recentMaterials ?? res.materials ?? prev.recentMaterials,
            overview: (res as any).overview ?? {
              title: res.overviewTitle ?? prev.overviewTitle,
              description: res.description ?? prev.description,
              learningOutcomes: res.learningOutcomes ?? prev.learningOutcomes,
              objectives: res.objectives ?? prev.objectives,
              thumbnailUrl: res.thumbnailUrl ?? prev.thumbnailUrl,
              thumbnailPublicId: (res as any).thumbnailPublicId ?? prev.overview?.thumbnailPublicId,
              weeklySchedule: res.weeklySchedule ?? prev.weeklySchedule,
              recentMaterials: (res as any).recentMaterials ?? res.materials ?? prev.recentMaterials,
              recommendedBooks: (res as any).overview?.recommendedBooks ?? prev.overview?.recommendedBooks ?? [],
            },
          }
        : prev,
    );
  };

  // ---------------------------------------------------------------------------
  // Overview
  // ---------------------------------------------------------------------------
  const handleSaveOverview = async (payload: {
    title: string;
    description: string;
    learningOutcome?: string;
    learningOutcomes?: string[];
    objectives?: string[];
    thumbnailUrl?: string;
    thumbnailPublicId?: string | null;
    weeklySchedule?: Array<{
      day: string;
      startTime: string;
      endTime: string;
      topic?: string;
      location?: string;
    }>;
    recentMaterials?: Array<{
      title: string;
      type: StudyMaterial["type"];
      url?: string;
      publicId?: string;
      content?: string;
      resourceType?: "image" | "video" | "raw" | "auto";
      originalFileName?: string;
      mimeType?: string;
      sizeBytes?: number;
    }>;
    recommendedBooks?: Array<{
      title: string;
      author: string;
      fileUrl?: string;
    }>;
  }) => {
    console.log('[TeacherClasses] handleSaveOverview called with payload:', payload);
    
    // Normalize learningOutcomes: accept either singular or plural
    const learningOutcomesArray = payload.learningOutcome 
      ? payload.learningOutcome.split('\n').map(o => o.trim()).filter(o => o.length > 0)
      : payload.learningOutcomes ?? [];
    
    // Optimistic update.
    setLocalCourse((prev) =>
      prev
        ? {
            ...prev,
            overviewTitle: payload.title,
            description: payload.description,
            learningOutcomes: learningOutcomesArray,
            objectives: payload.objectives ?? [],
            thumbnailUrl: payload.thumbnailUrl,
            weeklySchedule: payload.weeklySchedule ?? [],
            recentMaterials: payload.recentMaterials ?? [],
            overview: {
              title: payload.title,
              description: payload.description,
              learningOutcome: payload.learningOutcome ?? learningOutcomesArray.join('\n'),
              objectives: payload.objectives ?? [],
              thumbnailUrl: payload.thumbnailUrl,
              thumbnailPublicId: payload.thumbnailPublicId ?? undefined,
              weeklySchedule: payload.weeklySchedule ?? [],
              recentMaterials: payload.recentMaterials ?? [],
              recommendedBooks: payload.recommendedBooks ?? [],
            },
          }
        : prev,
    );
    setIsSaving(true);
    try {
      const courseId = await ensureCourseId();
      if (!courseId) return;
      // Build a valid learningOutcome string for DTO validation.
      const learningOutcomeString =
        (payload.learningOutcome ?? '').trim() ||
        (Array.isArray(payload.learningOutcomes)
          ? (payload.learningOutcomes[0] ?? '').trim()
          : '') ||
        String(payload.description ?? '').trim();

      const resolvedClassId = selectedCourse?.backendId ?? classRouteId;
      const resolvedSubjectId = selectedCourseCourse?.subjectId ?? courseRouteId;

      if (!resolvedClassId || !resolvedSubjectId) {
        toast.error('Missing class or subject id for overview save.');
        return;
      }

      const apiPayload = {
        title: payload.title,
        description: String(payload.description ?? ''),
        learningOutcome: learningOutcomeString,
        thumbnailUrl: String(payload.thumbnailUrl ?? ''),
        thumbnailPublicId: payload.thumbnailPublicId ?? undefined,
        classId: resolvedClassId,
        subjectId: resolvedSubjectId,
        recommendedBooks: payload.recommendedBooks ?? [],
        teacherId: teacher.backendId ?? loadAuthSession()?.user.id,
      };

      console.log('[TeacherClasses] Sending simplified overview payload:', apiPayload);

      await apiAuthRequest(`/materials/course/${encodeURIComponent(courseId)}/overview`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(apiPayload),
      });
      console.log('[TeacherClasses] Overview saved successfully');
      setOverviewLastSavedAt(new Date().toISOString());
      toast.success("Overview saved.");
    } catch {
      toast.error("Failed to save overview.");
    } finally {
      setIsSaving(false);
    }
  };

  // ---------------------------------------------------------------------------
  // Course-level materials
  // ---------------------------------------------------------------------------
  const handlePatchRecommendedBooks = async (recommendedBooks: Array<{
    title: string;
    author: string;
    fileUrl?: string;
  }>) => {
    setIsSaving(true);
    try {
      const courseId = await ensureCourseId();
      if (!courseId) return;

      const classId = selectedCourse?.backendId ?? classRouteId;
      const subjectId = selectedCourseCourse?.subjectId ?? courseRouteId;

      if (!classId || !subjectId) {
        toast.error('Missing class or subject id for books update.');
        return;
      }

      // Call PATCH endpoint to add/update recommended books
      const response = await apiAuthRequest(`/materials/course/${encodeURIComponent(courseId)}/overview/recommended-books`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ recommendedBooks, classId, subjectId }),
      });

      // Update local state with patched books
      setLocalCourse((prev) =>
        prev
          ? {
              ...prev,
              overview: prev.overview
                ? {
                    ...prev.overview,
                    recommendedBooks,
                  }
                : prev.overview,
            }
          : prev,
      );

      toast.success("Recommended books added successfully.");
    } catch (error) {
      console.error('Failed to patch recommended books:', error);
      toast.error("Failed to add recommended books.");
    } finally {
      setIsSaving(false);
    }
  };

  // ---------------------------------------------------------------------------
  // Course-level materials
  // ---------------------------------------------------------------------------
  const handleAddMaterial = async (material: Omit<StudyMaterial, "id">) => {
    setIsSaving(true);
    try {
      const resolvedClassId = selectedCourse?.backendId ?? classRouteId;
      const resolvedSubjectId = selectedCourseCourse?.subjectId ?? courseRouteId;

      if (!resolvedClassId || !resolvedSubjectId) {
        toast.error("Missing class or subject id for material save.");
        return;
      }

      const ensuredCourse = await apiAuthRequest<any>(
        `/courses/ensure/${encodeURIComponent(resolvedClassId)}/${encodeURIComponent(resolvedSubjectId)}`,
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ name: selectedCourseCourse?.name ?? selectedCourse?.name ?? 'Course' }),
        },
      );

      const persistentCourseId = ensuredCourse.id;

      const created = await apiAuthRequest<any>(`/materials/course/${encodeURIComponent(persistentCourseId)}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          courseId: persistentCourseId,
          classId: resolvedClassId,
          subjectId: resolvedSubjectId,
          scope: 'material',
          title: material.title,
          type: material.type,
          url: material.url,
          publicId: material.publicId,
          content: material.content,
          description: material.content || material.title,
          learningOutcome: material.content || material.title,
          teacherId: teacher.backendId || loadAuthSession()?.user.id,
        }),
      });

      const nextMaterial = {
        id: created.id,
        title: created.title ?? material.title,
        type: created.type ?? material.type,
        url: created.url ?? material.url,
        publicId: created.publicId ?? material.publicId,
        content: created.content ?? material.content,
      };

      setLocalCourse((prev) =>
        prev
          ? {
              ...prev,
              materials: [...(prev.materials ?? []), nextMaterial as any],
              recentMaterials: [...(prev.recentMaterials ?? []), nextMaterial as any],
              overview: prev.overview
                ? {
                    ...prev.overview,
                    recentMaterials: [...(prev.overview.recentMaterials ?? []), nextMaterial as any],
                  }
                : prev.overview,
            }
          : prev,
      );

      toast.success("Material added.");
    } catch {
      toast.error("Failed to add material.");
    } finally {
      setIsSaving(false);
    }
  };

  const handleRemoveMaterial = async (materialId: string) => {
    setIsSaving(true);
    try {
      await apiAuthRequest(`/materials/${String(materialId)}`, {
        method: 'DELETE',
      });

      setLocalCourse((prev) =>
        prev
          ? {
              ...prev,
              materials: (prev.materials ?? []).filter((material) => String((material as any).id) !== String(materialId)),
              recentMaterials: (prev.recentMaterials ?? []).filter((material) => String((material as any).id) !== String(materialId)),
              overview: prev.overview
                ? {
                    ...prev.overview,
                    recentMaterials: (prev.overview.recentMaterials ?? []).filter(
                      (material) => String((material as any).id) !== String(materialId),
                    ),
                  }
                : prev.overview,
            }
          : prev,
      );

      toast.success("Material removed.");
    } catch {
      toast.error("Failed to remove material.");
    } finally {
      setIsSaving(false);
    }
  };

  // ---------------------------------------------------------------------------
  // Chapters
  // ---------------------------------------------------------------------------
  const handleAddChapter = async (data: {
    chapterNumber: number;
    chapterName: string;
    description?: string;
  }) => {
    setIsSaving(true);
    try {
      setLocalCourse((prev) =>
        prev
          ? {
              ...prev,
              chapters: [
                ...(prev.chapters ?? []),
                {
                  id: data.chapterNumber,
                  chapterNumber: data.chapterNumber,
                  chapterName: data.chapterName,
                  description: data.description,
                  topics: [],
                  materials: [],
                },
              ],
            }
          : prev,
      );
      toast.success("Chapter added.");
    } catch {
      toast.error("Failed to add chapter.");
    } finally {
      setIsSaving(false);
    }
  };

  const handleUpdateChapter = async (
    chapterId: number | string,
    patch: {
      chapterNumber?: number;
      chapterName?: string;
      description?: string;
    },
  ) => {
    const courseId = backendCourseId;
    if (!courseId) return;
    // Optimistic.
    setLocalCourse((prev) =>
      prev
        ? {
            ...prev,
            chapters: (prev.chapters ?? []).map((ch) =>
              ch.id === chapterId ? { ...ch, ...patch } : ch,
            ),
          }
        : prev,
    );
    try {
      void patch;
    } catch {
      toast.error("Failed to update chapter.");
    }
  };
  const handleAddChapterMaterial = async (
    chapterId: number | string,
    material: Omit<StudyMaterial, "id">,
  ) => {
    setIsSaving(true);
    try {
      setLocalCourse((prev) =>
        prev
          ? {
              ...prev,
              materials: [
                ...(prev.materials ?? []),
                {
                  id: `${Date.now()}`,
                  title: material.title,
                  type: material.type,
                  url: material.url,
                  publicId: material.publicId,
                  content: material.content,
                },
              ],
            }
          : prev,
      );
      toast.success("Chapter material added.");
    } catch {
      toast.error("Failed to add chapter material.");
    } finally {
      setIsSaving(false);
    }
  };

  // ---------------------------------------------------------------------------
  // Topics
  // ---------------------------------------------------------------------------
  const handleAddTopic = async (
    chapterId: number | string,
    topicName: string,
  ) => {
    setIsSaving(true);
    try {
      setLocalCourse((prev) =>
        prev
          ? {
              ...prev,
              chapters: (prev.chapters ?? []).map((chapter) =>
                chapter.id === chapterId
                  ? {
                      ...chapter,
                      topics: [
                        ...(chapter.topics ?? []),
                        {
                          id: `${Date.now()}`,
                          topicName,
                          materials: [],
                        },
                      ],
                    }
                  : chapter,
              ),
            }
          : prev,
      );
      toast.success("Topic added.");
    } catch {
      toast.error("Failed to add topic.");
    } finally {
      setIsSaving(false);
    }
  };

  const handleUpdateTopic = async (
    chapterId: number | string,
    topicId: number | string,
    topicName: string,
  ) => {
    const courseId = backendCourseId;
    if (!courseId) return;
    // Optimistic.
    setLocalCourse((prev) =>
      prev
        ? {
            ...prev,
            chapters: (prev.chapters ?? []).map((ch) =>
              ch.id === chapterId
                ? {
                    ...ch,
                    topics: (ch.topics ?? []).map((t) =>
                      t.id === topicId ? { ...t, topicName } : t,
                    ),
                  }
                : ch,
            ),
          }
        : prev,
    );
    try {
      void topicName;
    } catch {
      toast.error("Failed to update topic.");
    }
  };

  const handleAddTopicMaterial = async (
    chapterId: number | string,
    topicId: number | string,
    material: Omit<StudyMaterial, "id">,
  ) => {
    setIsSaving(true);
    try {
      setLocalCourse((prev) =>
        prev
          ? {
              ...prev,
              chapters: (prev.chapters ?? []).map((chapter) =>
                chapter.id === chapterId
                  ? {
                      ...chapter,
                      topics: (chapter.topics ?? []).map((topic) =>
                        topic.id === topicId
                          ? {
                              ...topic,
                              materials: [
                                ...(topic.materials ?? []),
                                {
                                  id: `${Date.now()}`,
                                  title: material.title,
                                  type: material.type,
                                  url: material.url,
                                  publicId: material.publicId,
                                  content: material.content,
                                },
                              ],
                            }
                          : topic,
                      ),
                    }
                  : chapter,
              ),
            }
          : prev,
      );
      toast.success("Topic material added.");
    } catch {
      toast.error("Failed to add topic material.");
    } finally {
      setIsSaving(false);
    }
  };

  const handleDeleteChapter = async (chapterId: number | string) => {
    const courseId = backendCourseId;
    if (!courseId) return;
    if (!confirm("Are you sure you want to delete this chapter and all its topics?")) return;

    setIsSaving(true);
    try {
      setLocalCourse((prev) =>
        prev
          ? {
              ...prev,
              chapters: (prev.chapters ?? []).filter((chapter) => chapter.id !== chapterId),
            }
          : prev,
      );
      toast.success("Chapter deleted.");
    } catch {
      toast.error("Failed to delete chapter.");
    } finally {
      setIsSaving(false);
    }
  };

  const handleDeleteTopic = async (chapterId: number | string, topicId: number | string) => {
    const courseId = backendCourseId;
    if (!courseId) return;
    if (!confirm("Are you sure you want to delete this topic?")) return;

    setIsSaving(true);
    try {
      setLocalCourse((prev) =>
        prev
          ? {
              ...prev,
              chapters: (prev.chapters ?? []).map((chapter) =>
                chapter.id === chapterId
                  ? {
                      ...chapter,
                      topics: (chapter.topics ?? []).filter((topic) => topic.id !== topicId),
                    }
                  : chapter,
              ),
            }
          : prev,
      );
      toast.success("Topic deleted.");
    } catch {
      toast.error("Failed to delete topic.");
    } finally {
      setIsSaving(false);
    }
  };

  const handleSelectClass = (course: Course) => {
    if (onOpenClassCourses && course.backendId) {
      onOpenClassCourses(course.backendId);
      return;
    }
    onSelectClass(course);
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center py-16 text-muted-foreground gap-2">
        <span className="spinner h-4 w-4" />
        Loading classes...
      </div>
    );
  }

  // Show loading state when navigating to materials route but course data hasn't loaded yet
  if (classRouteId && courseRouteId && !localCourse && !selectedCourseCourse) {
    return (
      <div className="flex items-center justify-center py-16 text-muted-foreground gap-2">
        <span className="spinner h-4 w-4" />
        Loading course materials...
      </div>
    );
  }

  if (classRouteId && !courseRouteId) {
    const classLabel = routeSelectedClass
      ? classNameMap[routeSelectedClass.backendId] || routeSelectedClass.name
      : classRouteId;

    return (
      <div className="space-y-6 max-w-7xl mx-auto px-4 sm:px-6 py-6">
        <button
          onClick={() => {
            if (onBackToClasses) {
              onBackToClasses();
              return;
            }
            onSelectClass(null);
          }}
          className="inline-flex items-center gap-2 text-sm font-medium text-muted-foreground hover:text-foreground transition-all group"
        >
          <ArrowLeft className="h-4 w-4 transition-transform group-hover:-translate-x-1" />
          Back to Classes
        </button>

        <div className="rounded-2xl bg-card border border-border/60 shadow-sm p-6">
          <h1 className="text-2xl font-bold text-foreground">{classLabel} Courses</h1>
          <p className="text-sm text-muted-foreground mt-1">
            Select a course to open its materials page.
          </p>
        </div>

        {coursesForSelectedClass.length === 0 ? (
          <div className="rounded-xl border border-dashed border-border bg-muted/10 p-5 text-sm text-muted-foreground">
            No courses are assigned to you for this class.
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {coursesForSelectedClass.map((course) => (
              <button
                key={course.id}
                onClick={() => {
                  if (onOpenCourseMaterials) {
                    onOpenCourseMaterials(classRouteId, course.subjectId ?? course.courseId ?? course.id);
                  } else {
                    setSelectedCourseId(course.id);
                  }
                }}
                className="text-left rounded-xl border border-border bg-card p-5 hover:border-primary/40 hover:bg-primary/5 transition-all"
              >
                <h3 className="text-lg font-semibold text-foreground">{course.name}</h3>
                <p className="text-xs text-muted-foreground mt-1 font-mono">{course.code}</p>
                <p className="text-sm text-muted-foreground mt-3 line-clamp-2">
                  {course.description || "No description."}
                </p>
                <p className="text-xs text-muted-foreground mt-3">
                  Materials: {course.materialsCount}
                </p>
              </button>
            ))}
          </div>
        )}
      </div>
    );
  }

  if ((localCourse || selectedCourseCourse) && classRouteId && courseRouteId) {
    const courseLabel = selectedCourseCourse?.name ?? localCourse?.name ?? "Course";
    return (
      <div className="space-y-6 max-w-7xl mx-auto px-4 sm:px-6 py-6">
        <button
          onClick={() => {
            if (onBackToClassCourses) {
              onBackToClassCourses(classRouteId);
              return;
            }
            onSelectClass(null);
          }}
          className="inline-flex items-center gap-2 text-sm font-medium text-muted-foreground hover:text-foreground transition-all group"
        >
          <ArrowLeft className="h-4 w-4 transition-transform group-hover:-translate-x-1" />
          Back to Courses
        </button>

        <div className="rounded-2xl bg-card border border-border/60 shadow-sm p-6">
          <h1 className="text-2xl font-bold text-foreground">{courseLabel}</h1>
          <p className="text-sm text-muted-foreground mt-1">Course Materials</p>
        </div>

        {!backendCourseId ? (
          <div className="rounded-xl border border-dashed border-border bg-muted/10 p-5 text-sm text-muted-foreground">
            Course is loading. Please wait.
          </div>
        ) : (
          <div className="rounded-2xl bg-card border border-border/60 shadow-sm p-6">
            <MaterialsTab
              selectedClass={localCourse}
              onAddMaterial={handleAddMaterial}
              onRemoveMaterial={handleRemoveMaterial}
              onSaveOverview={handleSaveOverview}
                            onPatchRecommendedBooks={handlePatchRecommendedBooks}
              isSaving={isSaving}
            />
          </div>
        )}
      </div>
    );
  }

  if (localCourse) {
    return (
      <div className="space-y-6 max-w-7xl mx-auto px-4 sm:px-6 py-6">
        <button
          onClick={() => onSelectClass(null)}
          className="inline-flex items-center gap-2 text-sm font-medium text-muted-foreground hover:text-foreground transition-all group"
        >
          <ArrowLeft className="h-4 w-4 transition-transform group-hover:-translate-x-1" />
          Back to Classes
        </button>

        {/* Class header */}
        <div className="rounded-2xl bg-card border border-border/60 shadow-sm hover:shadow-md transition-all duration-300 p-6 md:p-8">
          <div className="flex flex-col lg:flex-row lg:items-start lg:justify-between gap-6">
            <div className="space-y-3">
              <h1 className="text-3xl font-bold tracking-tight text-foreground">
                {classNameMap[localCourse.backendId] || localCourse.name}
              </h1>
              <div className="flex flex-wrap items-center gap-x-4 gap-y-2 text-sm text-muted-foreground">
                <span className="font-mono">{localCourse.code}</span>
                <span className="hidden sm:inline">•</span>
                <span>{localCourse.room}</span>
                <span className="hidden sm:inline">•</span>
                <span className="flex items-center gap-1">
                  <Clock className="h-3.5 w-3.5" />
                  {localCourse.schedule}
                </span>
              </div>
              <p className="text-sm text-muted-foreground max-w-2xl leading-relaxed">
                {localCourse.description}
              </p>
            </div>

            <div className="flex flex-wrap gap-4">
              {[
                { label: "Students", value: classStudents.length, icon: Users },
                { label: "Assessments", value: classGradebook.length, icon: BookOpen },
                { label: "Avg Score", value: `${formatAssessmentAverage()}%`, icon: TrendingUp },
              ].map((stat) => (
                <div key={stat.label} className="group relative rounded-xl bg-muted/30 p-4 min-w-[110px] text-center hover:bg-muted/40 transition-all">
                  <div className="h-10 w-10 rounded-full bg-primary/10 text-primary flex items-center justify-center mx-auto mb-2">
                    <stat.icon className="h-5 w-5" />
                  </div>
                  <p className="text-xl font-bold text-foreground">{stat.value}</p>
                  <p className="text-xs text-muted-foreground uppercase tracking-wide">{stat.label}</p>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Tabs */}
        <div className="rounded-xl border border-border/60 bg-card p-4">
          <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground mb-2">
            Courses In This Class
          </p>
          {coursesForSelectedClass.length === 0 ? (
            <div className="rounded-lg bg-amber-50 border border-amber-200 p-3">
              <p className="text-sm text-amber-800">
                ℹ️ No courses assigned yet. Contact your admin to add you to a course for this class.
              </p>
            </div>
          ) : (
            <select
              value={selectedCourseId ?? ""}
              onChange={(event) => setSelectedCourseId(event.target.value || null)}
              className="h-11 w-full rounded-xl border border-border bg-background px-4 text-sm text-foreground shadow-sm focus:outline-none focus:ring-2 focus:ring-primary/30"
            >
              <option value="">— Select a course to begin —</option>
              {coursesForSelectedClass.map((course) => (
                <option key={course.id} value={course.id}>
                  {course.name}
                </option>
              ))}
            </select>
          )}
        </div>

        {/* Tabs */}
        <div className="flex flex-wrap gap-1 border-b border-border/60 pb-2">
          {TAB_LABELS.map(({ id, label }) => (
            <button
              key={id}
              onClick={() => setActiveTab(id)}
              className={`px-5 py-2.5 text-sm font-medium rounded-lg transition-all ${
                activeTab === id
                  ? "bg-primary/10 text-primary shadow-sm"
                  : "text-muted-foreground hover:text-foreground hover:bg-muted/30"
              }`}
            >
              {label}
            </button>
          ))}
        </div>

        {/* Tab content */}
        <div className="rounded-2xl bg-card border border-border/60 shadow-sm p-6">
          {!backendCourseId ? (
            <div className="rounded-xl border border-dashed border-border bg-muted/10 p-5 text-sm text-muted-foreground">
              Please select a course from the dropdown above before adding materials or editing course content.
            </div>
          ) : null}

          {backendCourseId && activeTab === "overview" && (
            <OverviewTab
              selectedClass={localCourse}
              onSaveOverview={handleSaveOverview}
              onAddMaterial={handleAddMaterial}
              onDeleteMaterial={handleRemoveMaterial}
              titleDraft={titleDraft}
              onPatchRecommendedBooks={handlePatchRecommendedBooks}
              setTitleDraft={setTitleDraft}
              overviewDraft={overviewDraft}
              setOverviewDraft={setOverviewDraft}
              outcomesDraft={outcomesDraft}
              setOutcomesDraft={setOutcomesDraft}
              objectivesDraft={objectivesDraft}
              setObjectivesDraft={setObjectivesDraft}
              thumbnailDraft={thumbnailDraft}
              setThumbnailDraft={setThumbnailDraft}
              thumbnailPublicId={thumbnailPublicId}
              setThumbnailPublicId={setThumbnailPublicId}
              thumbnailUploading={thumbnailUploading}
              setThumbnailUploading={setThumbnailUploading}
              overviewLastSavedAt={overviewLastSavedAt}
              weeklySchedule={weeklySchedule}
              setWeeklySchedule={setWeeklySchedule}
              recentMaterials={recentMaterials}
              setRecentMaterials={setRecentMaterials}
              materialTitle={materialTitle}
              setMaterialTitle={setMaterialTitle}
              materialUrl={materialUrl}
              setMaterialUrl={setMaterialUrl}
              materialContent={materialContent}
              setMaterialContent={setMaterialContent}
              materialFile={materialFile}
              setMaterialFile={setMaterialFile}
            />
          )}

          {backendCourseId && activeTab === "chapters" && (
            <ChaptersTab
              selectedClass={localCourse}
              expandedChapters={expandedChapters}
              expandedTopics={expandedTopics}
              onToggleChapter={(id) =>
                setExpandedChapters((prev) => {
                  const next = new Set(prev);
                  if (next.has(id)) {
                    next.delete(id);
                  } else {
                    next.add(id);
                  }
                  return next;
                })
              }
              onToggleTopic={(id) =>
                setExpandedTopics((prev) => {
                  const next = new Set(prev);
                  if (next.has(id)) {
                    next.delete(id);
                  } else {
                    next.add(id);
                  }
                  return next;
                })
              }
              onAddChapter={handleAddChapter}
              onUpdateChapter={handleUpdateChapter}
              onDeleteChapter={handleDeleteChapter}
              onAddChapterMaterial={handleAddChapterMaterial}
              onAddTopic={handleAddTopic}
              onUpdateTopic={handleUpdateTopic}
              onDeleteTopic={handleDeleteTopic}
              onAddTopicMaterial={handleAddTopicMaterial}
            />
          )}

          {backendCourseId && activeTab === "materials" && (
            <MaterialsTab
              selectedClass={localCourse}
              onAddMaterial={handleAddMaterial}
              onRemoveMaterial={handleRemoveMaterial}
              onSaveOverview={handleSaveOverview}
              isSaving={isSaving}
            />
          )}

          {backendCourseId && activeTab === "students" && (
            <StudentsSection
              classStudents={classStudents}
              teacher={teacher}
              expandedStudentId={expandedStudentId}
              onToggleStudent={(id) =>
                setExpandedStudentId((prev) => (prev === id ? null : id))
              }
            />
          )}

          {backendCourseId && activeTab === "assessments" && (
            <div className="space-y-8">
              <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                <div className="rounded-xl border border-border/60 bg-muted/15 p-4">
                  <p className="text-xs text-muted-foreground">Assignment Submissions</p>
                  <p className="text-xl font-bold text-foreground mt-1">
                    {classAssignmentSubmissions.length}/{Math.max(classAssignments.length * Math.max(classStudents.length, 1), 1)}
                  </p>
                </div>
                <div className="rounded-xl border border-border/60 bg-muted/15 p-4">
                  <p className="text-xs text-muted-foreground">Quiz Attempts</p>
                  <p className="text-xl font-bold text-foreground mt-1">
                    {classQuizSubmissions.length}/{Math.max(classQuizzes.length * Math.max(classStudents.length, 1), 1)}
                  </p>
                </div>
                <div className="rounded-xl border border-border/60 bg-muted/15 p-4">
                  <p className="text-xs text-muted-foreground">Overall Performance</p>
                  <p className="text-xl font-bold text-foreground mt-1">{formatAssessmentAverage()}%</p>
                </div>
              </div>

              <div className="flex flex-wrap gap-2">
                <button
                  onClick={() => onNavigate("assignments")}
                  className="inline-flex items-center gap-2 rounded-lg border border-primary px-3 py-2 text-sm text-primary hover:bg-primary/10"
                >
                  Manage Assignments
                </button>
                <button
                  onClick={() => onNavigate("checkQuizzes")}
                  className="inline-flex items-center gap-2 rounded-lg border border-primary px-3 py-2 text-sm text-primary hover:bg-primary/10"
                >
                  Manage Quiz Results
                </button>
              </div>

              {/* Assignments */}
              <div>
                <h3 className="text-lg font-semibold text-foreground mb-4 flex items-center gap-2">
                  <BookOpen className="h-5 w-5 text-primary" /> Assignments
                </h3>
                {classAssignments.length === 0 ? (
                  <p className="text-sm text-muted-foreground bg-muted/20 rounded-xl p-4 text-center">No assignments found for this class.</p>
                ) : (
                  <div className="space-y-3">
                    {classAssignments.map((assignment) => (
                      <div key={assignment.id} className="rounded-xl border border-border/60 p-4 hover:border-primary/30 transition-all">
                        <div className="flex items-start justify-between gap-4">
                          <div>
                            <p className="font-semibold text-foreground">{assignment.title}</p>
                            <p className="text-xs text-muted-foreground mt-1">
                              {assignment.subject} · Due {new Date(assignment.dueDate).toLocaleDateString()}
                            </p>
                            {assignment.description && (
                              <p className="text-sm text-muted-foreground mt-2 line-clamp-2">{assignment.description}</p>
                            )}
                          </div>
                          <span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-medium text-primary">
                            {assignment.totalMarks} marks
                          </span>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* Quizzes */}
              <div>
                <h3 className="text-lg font-semibold text-foreground mb-4 flex items-center gap-2">
                  <BookOpen className="h-5 w-5 text-primary" /> Quizzes
                </h3>
                {classQuizzes.length === 0 ? (
                  <p className="text-sm text-muted-foreground bg-muted/20 rounded-xl p-4 text-center">No quizzes found for this class.</p>
                ) : (
                  <div className="space-y-3">
                    {classQuizzes.map((quiz) => (
                      <div key={quiz.id} className="rounded-xl border border-border/60 p-4 hover:border-primary/30 transition-all">
                        <p className="font-semibold text-foreground">{quiz.title}</p>
                        <p className="text-xs text-muted-foreground mt-1">
                          {quiz.subject}
                          {quiz.chapterName ? ` · ${quiz.chapterName}` : ""}
                          {quiz.topicName ? ` · ${quiz.topicName}` : ""}
                        </p>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* Timetable */}
              <div>
                <h3 className="text-lg font-semibold text-foreground mb-4 flex items-center gap-2">
                  <Clock className="h-5 w-5 text-primary" /> Timetable
                </h3>
                {classTimetable.length === 0 ? (
                  <p className="text-sm text-muted-foreground bg-muted/20 rounded-xl p-4 text-center">No timetable slots found for this class.</p>
                ) : (
                  <div className="space-y-3">
                    {classTimetable.map((slot) => (
                      <div key={slot.id} className="rounded-xl border border-border/60 p-4 flex items-center justify-between gap-4 hover:border-primary/30 transition-all">
                        <div>
                          <p className="font-semibold text-foreground">{slot.subject}</p>
                          <p className="text-xs text-muted-foreground mt-1">{formatSlot(slot)}</p>
                        </div>
                        <span className="rounded-full bg-muted/30 px-3 py-1 text-xs text-muted-foreground">
                          {slot.teacherName}
                        </span>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </div>
          )}

          {backendCourseId && activeTab === "preview" && (
            <PreviewTab
              selectedClass={localCourse}
              studentCount={classStudents.length}
            />
          )}
        </div>
      </div>
    );
  }

  // Class list view
  return (
    <div className="space-y-8 animate-fade-in max-w-7xl mx-auto px-4 sm:px-6 py-6">
      <div className="text-center sm:text-left">
        <h1 className="text-2xl sm:text-3xl font-bold tracking-tight text-foreground flex items-center justify-center sm:justify-start gap-2">
          <BookOpen className="h-7 w-7 text-primary" /> My Classes
        </h1>
        <p className="text-sm text-muted-foreground mt-1">
          Live backend classes assigned to {teacher.name}.
        </p>
      </div>

      {myClasses.length === 0 ? (
        <div className="rounded-2xl bg-card border border-dashed border-border p-8 text-center text-muted-foreground">
          <BookOpen className="h-12 w-12 mx-auto mb-3 text-muted-foreground/30" />
          <p>No backend classes are assigned to this teacher yet.</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {myClasses.map((course) => {
            const gradeKeys = new Set(
              [course.backendId, course.name].filter(Boolean).map((v) => String(v)),
            );
            const courseStudents = students.filter((s) => gradeKeys.has(s.grade));
            const courseAssessments = gradebookEntries.filter((e) =>
              gradeKeys.has(e.classGrade),
            );
            const courseSlots = timetableSlots.filter((s) => gradeKeys.has(s.className));
            const assignedCount =
              classCourseMap.get(String(course.backendId || course.id))?.assignedCourseCount ?? 0;

            return (
              <button
                key={course.id}
                onClick={() => handleSelectClass(course)}
                className="group text-left overflow-hidden rounded-2xl bg-card border border-border/60 shadow-sm hover:shadow-md transition-all duration-300 hover:-translate-y-1 p-6 focus-visible:ring-2 focus-visible:ring-primary/30"
              >
                <div className="flex items-start justify-between mb-4">
                  <div>
                    <h3 className="text-xl font-semibold text-foreground group-hover:text-primary transition-colors">
                      {classNameMap[course.backendId] || course.name}
                    </h3>
                    <p className="text-sm text-muted-foreground font-mono mt-0.5">{course.code}</p>
                  </div>
                  <div className="h-10 w-10 rounded-xl bg-primary/10 flex items-center justify-center group-hover:bg-primary/20 transition-colors">
                    <BookOpen className="h-5 w-5 text-primary" />
                  </div>
                </div>

                <div className="space-y-2 text-sm text-muted-foreground">
                  <div className="flex items-center gap-2">
                    <span className="font-medium">Academic Year:</span> {course.schedule}
                  </div>
                  <div className="flex items-center gap-2">
                    <Clock className="h-4 w-4" />
                    {courseSlots.length > 0 ? formatSlot(courseSlots[0]) : "No timetable slots"}
                  </div>
                  <div className="flex items-center gap-2">
                    <Users className="h-4 w-4" />
                    {courseStudents.length} Students
                  </div>
                  <div className="flex items-center gap-2">
                    <TrendingUp className="h-4 w-4" />
                    {courseAssessments.length} Assessments
                  </div>
                </div>

                <div className="mt-5">
                  <div className="flex justify-between text-xs mb-1.5">
                    <span className="text-muted-foreground">Assigned courses</span>
                    <span className="font-medium text-foreground">{assignedCount}</span>
                  </div>
                  <div className="h-1.5 bg-muted/50 rounded-full overflow-hidden">
                    <div className="h-full bg-primary rounded-full transition-all duration-300 group-hover:bg-primary/80" style={{ width: "100%" }} />
                  </div>
                </div>
              </button>
            );
          })}
        </div>
      )}
    </div>
  );
};

export default TeacherClasses;